name: 'olist_ecommerce'
version: '1.0.0'

profile: 'olist_ecommerce'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"

# ---MEDALLION ARCHITECTURE CONFIGURATION ---
models:
  olist_ecommerce:
    
    # Silver Layer: Lightweight views to clean raw data
    staging:
      +materialized: view
      
    # Intermediate: Pre-aggregations (can be views or tables)
    intermediate:
      +materialized: view
      
    # Gold Layer: Physically stored tables for fast dashboard performance
    marts:
      +materialized: table
