name: CI Pipeline - Terraform & dbt

# Only runs on Pull Requests to main (Dev -> PR workflow)
on:
  pull_request:
    branches:
      - main

jobs:
  
  # JOB 1: TERRAFORM INFRASTRUCTURE CHECK
  
  terraform-plan:
    name: 'Terraform Plan Check'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform 
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      
      - name: Setup HashiCorp Terraform
        uses: hashicorp/setup-terraform@v3
        
      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Plan
        # Enforces the plan and fails the action if it crashes.
        run: terraform plan -input=false
        env:
          # Dynamic Variables instead of Hardcoded Strings!
          TF_VAR_project_id: ${{ vars.GCP_PROJECT_ID }}
          TF_VAR_region: ${{ vars.GCP_REGION }}
          TF_VAR_bucket_name: ${{ vars.GCP_BUCKET_NAME }}
          TF_VAR_dataset_id: ${{ vars.GCP_DATASET_ID }}
          TF_VAR_is_development: true

  
  # JOB 2: DBT DATA QUALITY CHECK
  
  dbt-test:
    name: 'dbt Build & Test'
    needs: terraform-plan # Forces dbt to wait for Terraform!
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./olist_ecommerce 
        
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # Caches Python packages to speed up the pipeline
          
      - name: Install dbt-bigquery
        run: pip install dbt-bigquery
        
      - name: Run dbt Build
        # Builds the tables and runs your financial tests!
        run: dbt build --profiles-dir . --target dev